apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: shop-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sanketdesai09/auth-service:3f51698
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits: 
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: shop-platform
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 4000
      targetPort: 4000
