apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: shop-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: sanketdesai09/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: MONGO_URI
              value: "mongodb://auth-db:27017/authdb"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: shop-platform
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 4000
      targetPort: 4000
