apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-platform-ingress
  namespace: shop-platform
  annotations:
    # Magic Fix: Group 1 captures everything AFTER "/api/"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          # AUTH: /api/auth/register -> rewrites to /auth/register
          - path: /api/(auth.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 4000

          # PRODUCT: /api/products -> rewrites to /products
          - path: /api/(products.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-service
                port:
                  number: 5000

          # CATEGORIES: /api/categories -> rewrites to /categories
          - path: /api/(categories.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: product-service
                port:
                  number: 5000

          # CART: /api/cart -> rewrites to /cart
          - path: /api/(cart.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cart-service
                port:
                  number: 6001

          # ORDERS: /api/orders -> rewrites to /orders
          - path: /api/(orders.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: order-service
                port:
                  number: 7000

          # FRONTEND CATCH-ALL: Preserves exact asset paths (Group 1 is the whole path)
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
