apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: shop-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: sanketdesai09/order-service:3f51698
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: order-config
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: shop-platform
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 7000
      targetPort: 7000
